[package]
name = "archive"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.5"
chrono = "0.4.23"
tempfile = "3.3.0"
bincode = "2.0.0-rc.1"
mla = "1.3.0"
colors-transform = "0.2.11"

[dev-dependencies]
rand = "0.8.5"
